import{a as f,i as n,S as y}from"./assets/vendor-c493984e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const l={page:1,perPage:15},c=document.querySelector(".loader");function d(){c.style.display="flex"}function p(){c.style.display="none"}async function b(o){const r=new URLSearchParams({key:"44914505-36a6b847b314a6ef1bce975f7",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:l.perPage,page:l.page});d();try{return(await f.get(`https://pixabay.com/api/?${r}`)).data}catch(i){throw u(),i}finally{p()}}function u(o){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}const S=document.querySelector(".card-container");function x(o){const r=o.map(({webformatURL:a,largeImageURL:e,tags:t,likes:s,views:h,comments:m,downloads:g})=>`<li class="gallery-item">
            <a class="gallery-link" href="${e}">
                <img class="gallery-image" src="${a}" alt="${t}" width="360" height="200"/>
                <ul class="gallery-text-list">
                    <li class="gallery-text-item"><h3>Likes</h3><p>${s}</p></li>
                    <li class="gallery-text-item"><h3>Views</h3><p>${h}</p></li>
                    <li class="gallery-text-item"><h3>Comments</h3><p>${m}</p></li>
                    <li class="gallery-text-item"><h3>Downloads</h3><p>${g}</p></li>
                </ul>
            </a>
        </li>`).join("");S.innerHTML=r,new y(".card-container a",{captionsData:"alt",captionPosition:"bottom"}).refresh()}const P=document.querySelector(".search-form");P.addEventListener("submit",w);function w(o){o.preventDefault();const r=o.currentTarget,i=r.elements.query.value.trim();i===""?n.error({title:"Error",message:"Please enter a search term!",position:"topRight"}):b(i).then(a=>{a.hits.length===0&&n.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),x(a.hits)}).catch(u).finally(()=>{r.reset(),p()})}
//# sourceMappingURL=commonHelpers.js.map
